/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author estef
 */
public class AgregarVis extends javax.swing.JFrame {

    /**
     * Creates new form AgregarVis
     */
    public AgregarVis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputNombreVis = new javax.swing.JTextField();
        NombreVisi = new javax.swing.JLabel();
        EdadVisi = new javax.swing.JLabel();
        InputEdadVis = new javax.swing.JTextField();
        Fechavisi = new javax.swing.JLabel();
        InputFechaVisi = new javax.swing.JTextField();
        InputNacionalVisi = new javax.swing.JTextField();
        NacionalVisi = new javax.swing.JLabel();
        IDvisit = new javax.swing.JLabel();
        InputIDVisi = new javax.swing.JTextField();
        Guardarvisi = new javax.swing.JButton();
        MenuVisi = new javax.swing.JButton();
        AtrasVisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ingrese los datos del visitante");

        InputNombreVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNombreVisActionPerformed(evt);
            }
        });

        NombreVisi.setText("Nombre");

        EdadVisi.setText("Edad ");

        InputEdadVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEdadVisActionPerformed(evt);
            }
        });

        Fechavisi.setText("Fecha ingreso");

        InputFechaVisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFechaVisiActionPerformed(evt);
            }
        });

        InputNacionalVisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNacionalVisiActionPerformed(evt);
            }
        });

        NacionalVisi.setText("Nacionalidad");

        IDvisit.setText("ID visitante");

        InputIDVisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIDVisiActionPerformed(evt);
            }
        });

        Guardarvisi.setBackground(new java.awt.Color(102, 102, 102));
        Guardarvisi.setForeground(new java.awt.Color(255, 255, 255));
        Guardarvisi.setText("Guardar");
        Guardarvisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarvisiActionPerformed(evt);
            }
        });

        MenuVisi.setBackground(new java.awt.Color(102, 102, 102));
        MenuVisi.setForeground(new java.awt.Color(255, 255, 255));
        MenuVisi.setText("Menu");
        MenuVisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVisiActionPerformed(evt);
            }
        });

        AtrasVisi.setBackground(new java.awt.Color(102, 102, 102));
        AtrasVisi.setForeground(new java.awt.Color(255, 255, 255));
        AtrasVisi.setText("Atras");
        AtrasVisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasVisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Guardarvisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtrasVisi)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuVisi)
                .addGap(648, 648, 648))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputIDVisi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDvisit, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNacionalVisi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NacionalVisi)
                    .addComponent(InputFechaVisi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fechavisi)
                    .addComponent(InputEdadVis, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdadVisi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNombreVis, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreVisi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 452, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(NombreVisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputNombreVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EdadVisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputEdadVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fechavisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputFechaVisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NacionalVisi)
                .addGap(18, 18, 18)
                .addComponent(InputNacionalVisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IDvisit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputIDVisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardarvisi)
                    .addComponent(AtrasVisi))
                .addGap(18, 18, 18)
                .addComponent(MenuVisi)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasVisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasVisiActionPerformed
        RegistroDeVisitantes rVisi = new RegistroDeVisitantes();
        rVisi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasVisiActionPerformed

    private void MenuVisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVisiActionPerformed
        Menu menu1 = new Menu();
        menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuVisiActionPerformed

    private void GuardarvisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarvisiActionPerformed

    }//GEN-LAST:event_GuardarvisiActionPerformed

    private void InputIDVisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIDVisiActionPerformed
        String IDVisit = InputIDVisi.getText();
    }//GEN-LAST:event_InputIDVisiActionPerformed

    private void InputNacionalVisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNacionalVisiActionPerformed
        String NacionalVisi = InputFechaVisi.getText();
    }//GEN-LAST:event_InputNacionalVisiActionPerformed

    private void InputFechaVisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFechaVisiActionPerformed
        String FechaVisi = InputFechaVisi.getText();
    }//GEN-LAST:event_InputFechaVisiActionPerformed

    private void InputEdadVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEdadVisActionPerformed
        String EdadVis = InputEdadVis.getText();
    }//GEN-LAST:event_InputEdadVisActionPerformed

    private void InputNombreVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNombreVisActionPerformed
        String NombreVis = InputNombreVis.getText();
    }//GEN-LAST:event_InputNombreVisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasVisi;
    private javax.swing.JLabel EdadVisi;
    private javax.swing.JLabel Fechavisi;
    private javax.swing.JButton Guardarvisi;
    private javax.swing.JLabel IDvisit;
    private javax.swing.JTextField InputEdadVis;
    private javax.swing.JTextField InputFechaVisi;
    private javax.swing.JTextField InputIDVisi;
    private javax.swing.JTextField InputNacionalVisi;
    private javax.swing.JTextField InputNombreVis;
    private javax.swing.JButton MenuVisi;
    private javax.swing.JLabel NacionalVisi;
    private javax.swing.JLabel NombreVisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
