/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author estef
 */
public class AgregarHabi extends javax.swing.JFrame {

    /**
     * Creates new form AgregarHabi
     */
    public AgregarHabi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputNombreHabi = new javax.swing.JTextField();
        NombreHabi = new javax.swing.JLabel();
        TipoHabi = new javax.swing.JLabel();
        InputTipoHabi = new javax.swing.JTextField();
        GuardarHabi = new javax.swing.JButton();
        MenuHabi = new javax.swing.JButton();
        AtrasHabi = new javax.swing.JButton();
        Capacidad = new javax.swing.JLabel();
        InputCapaciHabi = new javax.swing.JTextField();
        InputIDHabi = new javax.swing.JTextField();
        IDHabi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ingrese los datos del Habitat");

        InputNombreHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNombreHabiActionPerformed(evt);
            }
        });

        NombreHabi.setText("Nombre");

        TipoHabi.setText("Tipo de Ambiente");

        InputTipoHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTipoHabiActionPerformed(evt);
            }
        });

        GuardarHabi.setBackground(new java.awt.Color(102, 102, 102));
        GuardarHabi.setForeground(new java.awt.Color(255, 255, 255));
        GuardarHabi.setText("Guardar");
        GuardarHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarHabiActionPerformed(evt);
            }
        });

        MenuHabi.setBackground(new java.awt.Color(102, 102, 102));
        MenuHabi.setForeground(new java.awt.Color(255, 255, 255));
        MenuHabi.setText("Menu");
        MenuHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHabiActionPerformed(evt);
            }
        });

        AtrasHabi.setBackground(new java.awt.Color(102, 102, 102));
        AtrasHabi.setForeground(new java.awt.Color(255, 255, 255));
        AtrasHabi.setText("Atras");
        AtrasHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasHabiActionPerformed(evt);
            }
        });

        Capacidad.setText("Capacidad");

        InputCapaciHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCapaciHabiActionPerformed(evt);
            }
        });

        InputIDHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIDHabiActionPerformed(evt);
            }
        });

        IDHabi.setText("ID Habitat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputIDHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputCapaciHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputTipoHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNombreHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 413, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(GuardarHabi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtrasHabi)
                .addGap(223, 223, 223))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(605, 605, 605)
                        .addComponent(MenuHabi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(NombreHabi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputNombreHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoHabi)
                .addGap(18, 18, 18)
                .addComponent(InputTipoHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Capacidad)
                .addGap(18, 18, 18)
                .addComponent(InputCapaciHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(IDHabi)
                .addGap(18, 18, 18)
                .addComponent(InputIDHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(MenuHabi)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtrasHabi)
                    .addComponent(GuardarHabi))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasHabiActionPerformed
        RegistroDeHabitats atrasHabi = new RegistroDeHabitats();
        atrasHabi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasHabiActionPerformed

    private void MenuHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHabiActionPerformed
        Menu menu1 = new Menu();
        menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuHabiActionPerformed

    private void GuardarHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarHabiActionPerformed

    }//GEN-LAST:event_GuardarHabiActionPerformed

    private void InputTipoHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTipoHabiActionPerformed
        String TipoHabi = InputTipoHabi.getText();
    }//GEN-LAST:event_InputTipoHabiActionPerformed

    private void InputNombreHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNombreHabiActionPerformed
        String nombreHabi = InputNombreHabi.getText();
        JOptionPane.showMessageDialog(null, nombreHabi);
    }//GEN-LAST:event_InputNombreHabiActionPerformed

    private void InputCapaciHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCapaciHabiActionPerformed
         String CapaciHabi = InputCapaciHabi.getText();
        JOptionPane.showMessageDialog(null, CapaciHabi);
    }//GEN-LAST:event_InputCapaciHabiActionPerformed

    private void InputIDHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIDHabiActionPerformed
        String IDHabi = InputIDHabi.getText();
        JOptionPane.showMessageDialog(null, IDHabi);
    }//GEN-LAST:event_InputIDHabiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarHabi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasHabi;
    private javax.swing.JLabel Capacidad;
    private javax.swing.JButton GuardarHabi;
    private javax.swing.JLabel IDHabi;
    private javax.swing.JTextField InputCapaciHabi;
    private javax.swing.JTextField InputIDHabi;
    private javax.swing.JTextField InputNombreHabi;
    private javax.swing.JTextField InputTipoHabi;
    private javax.swing.JButton MenuHabi;
    private javax.swing.JLabel NombreHabi;
    private javax.swing.JLabel TipoHabi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
