/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

import PruebaProyecto.Home;
import PruebaProyecto.RegistroDeAnimales;
import PruebaProyecto.RegistroDeHabitats;
import PruebaProyecto.RegistroDeVisitantes;

/**
 *
 * @author XPC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegistroDeAnimalesMenu = new javax.swing.JButton();
        RegistroDeVisitantesMenu = new javax.swing.JButton();
        RegistroDeHabitatsMenu = new javax.swing.JButton();
        RegistroDeEventosMenu = new javax.swing.JButton();
        AtrasMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        RegistroDeAnimalesMenu.setBackground(new java.awt.Color(153, 153, 255));
        RegistroDeAnimalesMenu.setText("RegistroDeAnimales");
        RegistroDeAnimalesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDeAnimalesMenuActionPerformed(evt);
            }
        });

        RegistroDeVisitantesMenu.setBackground(new java.awt.Color(153, 153, 255));
        RegistroDeVisitantesMenu.setText("RegistroDeVisitantes");
        RegistroDeVisitantesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDeVisitantesMenuActionPerformed(evt);
            }
        });

        RegistroDeHabitatsMenu.setBackground(new java.awt.Color(153, 153, 255));
        RegistroDeHabitatsMenu.setText("RegistroDeHabitats");
        RegistroDeHabitatsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDeHabitatsMenuActionPerformed(evt);
            }
        });

        RegistroDeEventosMenu.setBackground(new java.awt.Color(153, 153, 255));
        RegistroDeEventosMenu.setText("RegistroDeEventos");
        RegistroDeEventosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDeEventosMenuActionPerformed(evt);
            }
        });

        AtrasMenu.setBackground(new java.awt.Color(153, 153, 255));
        AtrasMenu.setText("Atras");
        AtrasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(260, 769, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AtrasMenu)
                        .addGap(670, 670, 670))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegistroDeHabitatsMenu)
                            .addComponent(RegistroDeAnimalesMenu))
                        .addGap(652, 652, 652))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistroDeEventosMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistroDeVisitantesMenu))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(RegistroDeAnimalesMenu)
                .addGap(69, 69, 69)
                .addComponent(RegistroDeHabitatsMenu)
                .addGap(76, 76, 76)
                .addComponent(RegistroDeVisitantesMenu)
                .addGap(84, 84, 84)
                .addComponent(RegistroDeEventosMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(AtrasMenu)
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroDeAnimalesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDeAnimalesMenuActionPerformed
        RegistroDeAnimales AAL = new RegistroDeAnimales();
        AAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistroDeAnimalesMenuActionPerformed

    private void RegistroDeHabitatsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDeHabitatsMenuActionPerformed
        // TODO add your handling code here:
       RegistroDeHabitats habi  = new RegistroDeHabitats();
       habi.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_RegistroDeHabitatsMenuActionPerformed
                                     

    private void AtrasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasMenuActionPerformed
        Home atrasHome = new Home();
        atrasHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasMenuActionPerformed

    private void RegistroDeVisitantesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDeVisitantesMenuActionPerformed
        RegistroDeVisitantes visi = new RegistroDeVisitantes();
        visi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistroDeVisitantesMenuActionPerformed

    private void RegistroDeEventosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDeEventosMenuActionPerformed
        RegistroDeEventos even = new RegistroDeEventos();
        even.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistroDeEventosMenuActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasMenu;
    private javax.swing.JButton RegistroDeAnimalesMenu;
    private javax.swing.JButton RegistroDeEventosMenu;
    private javax.swing.JButton RegistroDeHabitatsMenu;
    private javax.swing.JButton RegistroDeVisitantesMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
