/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

/**
 *
 * @author estef
 */
public class TotalAdultos extends javax.swing.JFrame {

    /**
     * Creates new form TotalAdultos
     */
    public TotalAdultos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AtrasAdul = new javax.swing.JButton();
        MenuVisiAdul = new javax.swing.JButton();
        GuardarVisiAdul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AtrasAdul.setText("Atras");
        AtrasAdul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasAdulActionPerformed(evt);
            }
        });

        MenuVisiAdul.setBackground(new java.awt.Color(102, 102, 102));
        MenuVisiAdul.setForeground(new java.awt.Color(255, 255, 255));
        MenuVisiAdul.setText("Menu");
        MenuVisiAdul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVisiAdulActionPerformed(evt);
            }
        });

        GuardarVisiAdul.setText("Guardar");
        GuardarVisiAdul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarVisiAdulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(GuardarVisiAdul)
                .addGap(518, 518, 518)
                .addComponent(MenuVisiAdul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 682, Short.MAX_VALUE)
                .addComponent(AtrasAdul)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(586, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtrasAdul)
                    .addComponent(MenuVisiAdul)
                    .addComponent(GuardarVisiAdul))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuVisiAdulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVisiAdulActionPerformed
        Menu menu1 = new Menu();
        menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuVisiAdulActionPerformed

    private void AtrasAdulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasAdulActionPerformed
        RegistroDeVisitantes AtrasAdu = new RegistroDeVisitantes();
        AtrasAdu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasAdulActionPerformed

    private void GuardarVisiAdulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarVisiAdulActionPerformed
       
    }//GEN-LAST:event_GuardarVisiAdulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalAdultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalAdultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalAdultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalAdultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalAdultos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasAdul;
    private javax.swing.JButton GuardarVisiAdul;
    private javax.swing.JButton MenuVisiAdul;
    // End of variables declaration//GEN-END:variables
}
