/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

/**
 *
 * @author XPC
 */
public class Gestion extends javax.swing.JFrame {

    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        HorariAlimentacion = new javax.swing.JButton();
        AlimentosConsumidos = new javax.swing.JButton();
        FrecuenciaAlimetacion = new javax.swing.JButton();
        AtrasGestion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(119, 139, 81));

        HorariAlimentacion.setBackground(new java.awt.Color(0, 0, 0));
        HorariAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        HorariAlimentacion.setText("Horario de alimentacion");
        HorariAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariAlimentacionActionPerformed(evt);
            }
        });

        AlimentosConsumidos.setBackground(new java.awt.Color(0, 0, 0));
        AlimentosConsumidos.setForeground(new java.awt.Color(255, 255, 255));
        AlimentosConsumidos.setText("Alimentos consumidos");
        AlimentosConsumidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlimentosConsumidosActionPerformed(evt);
            }
        });

        FrecuenciaAlimetacion.setBackground(new java.awt.Color(0, 0, 0));
        FrecuenciaAlimetacion.setForeground(new java.awt.Color(255, 255, 255));
        FrecuenciaAlimetacion.setText("Frecuencia de alimentacion");
        FrecuenciaAlimetacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrecuenciaAlimetacionActionPerformed(evt);
            }
        });

        AtrasGestion.setText("Atras");
        AtrasGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasGestionActionPerformed(evt);
            }
        });

        jLabel1.setText("       Gestion de Alimentacion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(697, 697, 697)
                        .addComponent(AtrasGestion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(646, 646, 646)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(HorariAlimentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AlimentosConsumidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FrecuenciaAlimetacion)))))
                .addContainerGap(686, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(HorariAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AlimentosConsumidos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(FrecuenciaAlimetacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(AtrasGestion)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HorariAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariAlimentacionActionPerformed
        HorarioAliment HoraAli = new HorarioAliment();
        HoraAli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HorariAlimentacionActionPerformed

    private void AlimentosConsumidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentosConsumidosActionPerformed
        AlimentoConsumi AliConsu = new AlimentoConsumi();
        AliConsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AlimentosConsumidosActionPerformed

    private void FrecuenciaAlimetacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrecuenciaAlimetacionActionPerformed
         FrecuenciaAlimen FrecuAli = new FrecuenciaAlimen();
        FrecuAli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FrecuenciaAlimetacionActionPerformed

    private void AtrasGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasGestionActionPerformed
         Home atrasGES = new Home();
        atrasGES.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasGestionActionPerformed
 
                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlimentosConsumidos;
    private javax.swing.JButton AtrasGestion;
    private javax.swing.JButton FrecuenciaAlimetacion;
    private javax.swing.JButton HorariAlimentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
